task:
  alias: Go Lint
  container:
    image: golangci/golangci-lint:latest
  fetch_script:
    - go mod tidy
    - go generate ./...
    - go mod tidy
  # interfacebloat complains about miekg/pkcs11 API's that we can't change.
  # nosnakecase complains about miekg/pkcs11 API's that we can't change.
  lint_script: golangci-lint run --disable-all --enable errcheck,govet,ineffassign,staticcheck,structcheck,typecheck,unused,varcheck $GOLANGCI_ARGS -v --out-format json > lint-report.json
  matrix:
    - name: Go Lint New
      env:
        GOLANGCI_ARGS: "--new-from-rev=HEAD~"
    - name: Go Lint Mandatory
      env:
        GOLANGCI_ARGS: "--disable=cyclop,dupl,gci,godox,goerr113,gomnd,gosimple,ifshort,lll,nosnakecase,revive,varnamelen,wrapcheck"
    - name: Go Lint
      env:
        GOLANGCI_ARGS: ""
      allow_failures: true
  always:
    golangci_artifacts:
      path: lint-report.json
      type: text/json
      format: golangci
  
task:
  name: ShellCheck
  container:
    image: fedora:latest
    cpu: 1
    memory: 1G
  install_script: dnf install -y ShellCheck
  lint_script: bash testdata/shellcheck.bash
  
