task:
  alias: Go Lint
  container:
    image: golangci/golangci-lint:latest
  fetch_script:
    - go mod tidy
    - go generate ./...
    - go mod tidy
  install_script:
    - apt-get update
    - apt-get install -y libseccomp-dev pkg-config build-essential 
  lint_script: golangci-lint run --default=all --disable exhaustruct,gochecknoglobals,gochecknoinits,interfacebloat,gomoddirectives,lll,godot,tagalign,godox,depguard,funlen,gocognit,gosec,nestif,noinlineerr,cyclop,err113,mnd,varnamelen $GOLANGCI_ARGS -v --output.json.path=lint-report.json
  matrix:
    - name: Go Lint New
      env:
        GOLANGCI_ARGS: "--new-from-rev=HEAD~"
    - name: Go Lint Mandatory
      env:
        GOLANGCI_ARGS: "--disable=cyclop,dupl,godox,err113,mnd,staticcheck,lll,revive,varnamelen,wrapcheck"
    - name: Go Lint
      env:
        GOLANGCI_ARGS: ""
      allow_failures: true
  always:
    golangci_artifacts:
      path: lint-report.json
      type: text/json
      format: golangci

task:
  name: Socksification Tests
  container:
    image: golang:latest

  install_script:
    - apt-get update
    - apt-get install -y wget curl libseccomp-dev pkg-config build-essential

  build_script:
    - go mod tidy
    - go build -o sockstrace .
    - cd testdata && go mod tidy

  test_script:
    - (cd testdata && go run socks5_server.go &) && sleep 3
    - echo "Testing wget socksification..."
    - ./sockstrace wget --args "https://check.torproject.org" --proxy-pass pass --proxy-user user
    - echo "Testing curl socksification..."
    - ./sockstrace curl --args "https://check.torproject.org" --proxy-pass pass --proxy-user user

task:
  name: WebRTC Firefox Test
  container:
    image: golang:latest
  environment:
    NO_AUTH: "1"   # SOCKS5 server will run without auth

  install_script:
    - apt-get update
    - apt-get install -y libseccomp-dev pkg-config build-essential firefox-esr

  build_script:
    - go mod tidy
    - go build -o sockstrace .
    - cd testdata && go mod tidy

  test_script:
    - (cd testdata && go run socks5_server.go &) && sleep 3
     # Set up Firefox profile (hardcoded)
    - bash testdata/setup_firefox_profile.sh
    - echo "Testing Firefox via SOCKS5 proxy..."
    - timeout 60 ./sockstrace firefox --args "https://browserleaks.com/webrtc" --args "-P" --args "proxy-profile" --args "--headless" --logleaks || [ $? -eq 124 ]

task:
  name: ShellCheck
  container:
    image: fedora:latest
    cpu: 1
    memory: 1G
  install_script: dnf install -y ShellCheck
  lint_script: bash testdata/shellcheck.bash
  
